In [23]:
import numpy as pd

# random vector of size 20 with float in the range 1-20

vector = pd.random.uniform(1,20,20)
print("The original vector:" ,vector)

# reshape vector to 4 by 5

vector_reshaped = vector.reshape(4,5)
print("The reshaped vector before replace: ", vector_reshaped)

# replace max in each row by 0

vector_reshaped[pd.arange(4),vector_reshaped.argmax(axis=1)] = 0
print("The reshaped vector after replace: " ,vector_reshaped)


The original vector: [10.27383959  5.21896109 18.883563   15.46148727  8.52052664  9.47560874
  1.64838948 17.52199966 18.97490927  5.73678215 10.41700893 17.69003716
 18.78257513 19.22211409  1.45921782 19.16522296 18.52275716  7.20326935
 10.42568929  3.49345342]
The reshaped vector before replace:  [[10.27383959  5.21896109 18.883563   15.46148727  8.52052664]
 [ 9.47560874  1.64838948 17.52199966 18.97490927  5.73678215]
 [10.41700893 17.69003716 18.78257513 19.22211409  1.45921782]
 [19.16522296 18.52275716  7.20326935 10.42568929  3.49345342]]
The reshaped vector after replace:  [[10.27383959  5.21896109  0.         15.46148727  8.52052664]
 [ 9.47560874  1.64838948 17.52199966  0.          5.73678215]
 [10.41700893 17.69003716 18.78257513  0.          1.45921782]
 [ 0.         18.52275716  7.20326935 10.42568929  3.49345342]]


In [22]:
class Employee:
    count = 0
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count += 1
    def averageSalary(self):
        avg = self.salary / Employee.count
        return avg

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self, name, family, salary, department)

q1 = Employee("rajesh", "pradeep", 2000, "hr")
q2 = Employee("sunny", "srujith", 6000, "it")
q3 = FulltimeEmployee("david", "sams", 2000, "Manager")

print(q1.averageSalary())
print(q2.averageSalary())
print(q3.averageSalary())

666.6666666666666
2000.0
666.6666666666666
