In [5]:
class Employee:
    count = 0
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count += 1
    def averageSalary(self):
        avg = self.salary / Employee.count
        return avg

class FulltimeEmployee(Employee):
    def _init_(self, name, family, salary, department):
        Employee._init_(self, name, family, salary, department)

q1 = Employee("jack", "max", 7000, "Sales")
q2 = Employee("tom", "sam", 9000, "IT")
q3 = FulltimeEmployee("maxy", "Smith", 42000, "HR")

print(q1.averageSalary())
print(q2.averageSalary())
print(q3.averageSalary())

22333.333333333332
32666.666666666668
14000.0


In [6]:
import numpy as np

# random vector of size 20 with float in the range 1-20
vector = np.random.uniform(1,20,20)
print("The original vector:" ,vector)

# reshape vector to 4 by 5
vector_reshaped = vector.reshape(4,5)
print("The reshaped vector before replace: ", vector_reshaped)

# replace max in each row by 0
vector_reshaped[np.arange(4),vector_reshaped.argmax(axis=1)] = 0
print("The reshaped vector after replace: " ,vector_reshaped)

The original vector: [18.4462977   3.48359599  9.45578388 13.99324638  7.4703874  15.43845327
 17.43460715  7.25398857  7.92268322 19.45104836 17.27463045 15.1765132
 11.90797758 19.17681162 13.25708367 19.08350216  7.37498709 13.90063629
 14.37798072 17.77308451]
The reshaped vector before replace:  [[18.4462977   3.48359599  9.45578388 13.99324638  7.4703874 ]
 [15.43845327 17.43460715  7.25398857  7.92268322 19.45104836]
 [17.27463045 15.1765132  11.90797758 19.17681162 13.25708367]
 [19.08350216  7.37498709 13.90063629 14.37798072 17.77308451]]
The reshaped vector after replace:  [[ 0.          3.48359599  9.45578388 13.99324638  7.4703874 ]
 [15.43845327 17.43460715  7.25398857  7.92268322  0.        ]
 [17.27463045 15.1765132  11.90797758  0.         13.25708367]
 [ 0.          7.37498709 13.90063629 14.37798072 17.77308451]]
